### ISSUE TITLE
Don't explode when we encounter rest properties of destructuring

### ISSUE THREAD

**Issue by gknoy** [ciena-blueplanet/eslint-plugin-ocd#26]
# BUG REPORT

* [x] I have ensured that the issue isn't already reported
* [x] I have confirmed that the issue is reproducible with the latest released version
* [x] I have deleted the **FEATURE REQUEST / CODE CHANGE** section

## Summary
The tool explodes when doing some forms of destructuring assignment:
```js
const {foo, ...rest} = params
```
yields:
```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /redacted/node_modules/eslint-plugin-ocd/rules/sort-variable-declarator-properties.js:19:21
    at Array.forEach (native)
    at deterministicSort (/redacted/node_modules/eslint-plugin-ocd/rules/sort-variable-declarator-properties.js:15:8)
```

## Expected Behavior
The tool should correctly recognize that `...rest` (in these examples) is a valid item:
```js
const {foo, ...rest} = params  // valid sort ordering
const {zzz, ...rest} = params // fails sort ordering
```

## Actual Behavior
```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /redacted/node_modules/eslint-plugin-ocd/rules/sort-variable-declarator-properties.js:19:21
    at Array.forEach (native)
    at deterministicSort (/redacted/node_modules/eslint-plugin-ocd/rules/sort-variable-declarator-properties.js:15:8)
    at sortProperties (/redacted/node_modules/eslint-plugin-ocd/rules/sort-variable-declarator-properties.js:38:18)
    at VariableDeclarator (/redacted/node_modules/eslint-plugin-ocd/rules/sort-variable-declarator-properties.js:80:9)
    at listeners.(anonymous function).forEach.listener (/redacted/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (/redacted/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/redacted/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/redacted/node_modules/eslint/lib/util/node-event-generator.js:280:22)
```

## Steps to Reproduce
- Declare variables as in above example
- Run linting
- ~Profit~ Explode

---

* [ ] I am using the latest released version (can check with `npm ls <package-name>`)
* I am using these browsers:
  * [x] Chrome 64.0.x
  * [x] Firefox 60.0b1
* [x] My version of `Node` is: `6.9.1`
* [x] My version of `npm` is: `3.10.8`
* [x] My OS is: Darwin
* [x] Include ~the~ some contents of your _package.json_ file

```
  // ....
  "devDependencies": {
    "babel-core": "^6.25.0",
    "babel-eslint": "^8.2.1",
    "babel-loader": "^7.1.1",
    // ....
    "eslint": "^4.8.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-config-standard-react": "^5.0.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jasmine": "^2.9.1",
    "eslint-plugin-mocha": "^4.11.0",
    "eslint-plugin-node": "^5.1.1",
    "eslint-plugin-ocd": "^0.0.6",  // also verified with 1.0.6
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-react": "^7.6.0",
    "eslint-plugin-standard": "^3.0.1",
    // ....
  },
  // ....
```

**Comment by job13er** [comment]
I can confirm I saw the same thing.
